version: '3.4'

services:
  api:
    image: testequeue
    build:
      context: .
      dockerfile: ./Dockerfile
    command: node src/server.js
    links: 
      - rabbitmq
    depends_on: 
      - rabbitmq
    environment: 
      - RABBITMQ_HOST=rabbitmq
      - PORT=3000
      - MONGODB_HOST=mongodb
    restart: always
    ports: 
      - 3333:3000
  queue_receive:
    image: testequeue
    build:
      context: .
      dockerfile: ./Dockerfile
    command: node src/receive.js
    links: 
      - rabbitmq
    depends_on: 
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 4
    environment: 
      - RABBITMQ_HOST=rabbitmq
      - API_HOST=http://api:3000
    restart: always
  rabbitmq: 
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rabbitmq
    volumes: 
      - "./rabbitmq_data:/var/lib/rabbitmq/mnesia/"
  mongodb:
    image: mongo
    restart: always
    volumes: 
    - "./mongodb_data:/data/db"
    hostname: mongodb
    ports:
      - 27017:27017